# Configuration for Alacritty, the GPU enhanced terminal emulator.

window:
  padding:
    x: 3
    y: 3
  decorations: buttonless

font:
  normal:
    family: OperatorMono Nerd Font
    style: Book
  bold:
    family: OperatorMono Nerd Font
    style: Bold
  italic:
    family: OperatorMono Nerd Font
    style: Book Italic

  size: 12.0
  offset:
    x: 1
    y: 2
